version: '3.1'

services:
  parkingService:
    image: openjdk:11.0.6-jre
    container_name: Parking-Service
    ports:
      - 8081:8081
      - 8090:8090
    volumes:
      - /autoparking:/autoparking

  bookingService:
    image: openjdk:11.0.6-jre
    container_name: Booking-Service
    ports:
      - 8081:8081
    volumes:
      - /BookingServer:/BookingServer

  cancellationService:
    image: openjdk:11.0.6-jre
    container_name: Cancellation-Service
    ports:
      - 8082:8082
    volumes:
      - /CancellationServer:/CancellationServer
